server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    access_log  /var/log/nginx/host.access.log  main;

    root /usr/share/nginx/eu-bureauet;

    location ^~ /dataportal {
        rewrite  ^/dataportal/(.*) /$1 break;
        try_files $uri.html $uri /index.html;
    }

    location /dataportal/data {
        proxy_pass http://itsyourparliament.eu/debrief/data/;
    }
}
